---
title: "classify_raster_data"
author: "Jon Weiner"
date: "June 21, 2016"
output: html_document
---

#### Notes
"require" vs "library"
-Library imports 
-Require returns TRUE/FALSE

```{r import_libraries}
#load libraries
library(raster)
library(rgdal)
```

### Import Canopy Height Model

```{r import_CHM}
#import canopy height model
chm <- raster("../NEONdata/D17-California/TEAK/2013/lidar/TEAK_lidarCHM.tif")

plot(chm,
     main = "This plots using the raster package")

image(chm,
      main = "this just stretches the pixel")

```

### Deal with 0 values

```{r assign_values_na}
#assign no vegetation areas to NA to help with statistics

hist(chm)

chm[chm==0] <- NA

hist(chm,
     xlab = "Tree Height (m)")

```

### Import aspect data

```{r import_aspect}
#import aspect file

aspect <- raster("../NEONdata/D17-California/TEAK/2013/lidar/TEAK_lidarAspect.tif")

plot(aspect,
     main = "Aspect data for Teakettle site")

```

### Create Classification Matrix

```{r class_matrix}

#Create matrix
class.m <- c(0, 45, 1, 
             45, 135, NA, 
             135, 225, 2, 
             225, 315, NA, 
             315, 360, 1)

rcl.m <- matrix(class.m,
                ncol = 3,
                byrow = TRUE)

rcl.m

```

### Reclassify Raster

```{r perform_reclass}

asp.ns <- reclassify(aspect,
                     rcl.m)

plot(asp.ns,
     main = "North and South Facing Slopes")

```

### Export Geotiff

```{r export_tiff, eval = FALSE}

writeRaster(asp.ns,
            file = "../outputs/TEAK/Teak_NS_aspect.tif",
            options = "COMPRESS = LZW",
            NAflag = -9999)

```

### Create Raster Mask

```{r create_raster_mask}
asp.ns

ndvi <- raster("../NEONdata/D17-California/TEAK/2013/spectrometer/veg_index/TEAK_NDVI.tif")

plot(ndvi,
     main = "NDVI for teakettle field site")

#mask data
nFacing.ndvi <- mask(ndvi,
                     asp.ns)

plot(nFacing.ndvi)

```








